import React from "react";

export function TermsPage() {
  return (
    <div className="min-h-screen px-6 py-20">
      <div className="max-w-[800px] mx-auto">
        <a href="/" className="inline-block mb-8">
          <img src="/logo.png" alt="Aizen" className="w-12 h-12" />
        </a>
        <h1 className="text-4xl font-semibold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-[#86868b] mb-8">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>

        <div className="prose prose-invert max-w-none space-y-6 text-[#86868b]">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using Aizen ("the Software"), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, do not use the Software.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. License Grant</h2>
            <p>
              Vivy Technologies Co., Limited grants you a limited, non-exclusive, non-transferable license to use Aizen
              for personal or commercial purposes, subject to these terms.
            </p>
            <h3 className="text-lg font-medium text-white mb-2 mt-4">Free Version</h3>
            <p>The free version of Aizen may be used without charge, subject to any feature limitations.</p>
            <h3 className="text-lg font-medium text-white mb-2 mt-4">Aizen Pro</h3>
            <p>
              Aizen Pro requires a valid license. Each license is valid for a single user and may be activated on
              multiple devices owned by that user.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Restrictions</h2>
            <p>You may not:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Reverse engineer, decompile, or disassemble the Software</li>
              <li>Remove or alter any proprietary notices or labels</li>
              <li>Share, distribute, or sublicense your license key</li>
              <li>Use the Software for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Third-Party Services</h2>
            <p>
              Aizen integrates with third-party AI agents (Claude, Codex, Gemini, etc.). Your use of these services
              is subject to their respective terms of service. We are not responsible for the content or responses
              generated by these AI services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Disclaimer of Warranties</h2>
            <p>
              THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.
              WE DO NOT WARRANT THAT THE SOFTWARE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Limitation of Liability</h2>
            <p>
              IN NO EVENT SHALL VIVY TECHNOLOGIES CO., LIMITED BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF YOUR USE OF THE SOFTWARE.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Termination</h2>
            <p>
              We may terminate your license if you violate these terms. Upon termination, you must cease all use
              of the Software and destroy all copies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Governing Law</h2>
            <p>
              These terms shall be governed by the laws of Hong Kong SAR, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Contact</h2>
            <p>
              For questions about these Terms, contact us at:{" "}
              <a href="mailto:dev@aizen.win" className="text-blue-500 hover:underline">dev@aizen.win</a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/8">
          <a href="/" className="text-blue-500 hover:underline">← Back to Home</a>
        </div>
      </div>
    </div>
  );
}
